### ISSUE TITLE
Is there a way to ask about changes on dependent objects?

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-router#17]
That is, is there some way we could say in the services controller:

```ruby
if service.models_changed?
```

or even

```ruby
service.models.any?(&:changed?)
```

**Comment by mboneil10** [comment]
Probably not.

**Comment by dfaulken** [comment]
OK. Does the suggestion I made with `any?` not work?

**Comment by mboneil10** [comment]
Oh no. What do you mean by changes on these dependent objects? Are you referring to something like adding a new model to a service, or when an existing model under a service changes its attributes? Or are these both changes that you want to ask about?

**Comment by dfaulken** [comment]
All of the above. Any change which other services would need to know about.

**Comment by mboneil10** [comment]
Okay, to see about adding a new model to a service, I put a `binding.pry` in the else statement of [services_controller](https://github.com/umts/microservices-router/blob/master/app/controllers/services_controller.rb). 
Then, I ran your suggestion before and after the new model was created. The statement returned false in both places.

P.S. The rails API says for `changed?` that newly instantiated objects are unchanged.

**Comment by mboneil10** [comment]
Now I've changed an existing model's service_id and saved it. The `service.models.any?(&:changed?)` command returns false before and after the change.

**Comment by dfaulken** [comment]
Okay. Sounds like we need to keep the current workflow.

Out of curiosity, does the current workflow report that a change is made when the only change is that a model is removed?

**Comment by mboneil10** [comment]
It reports a change is made when a model is created.

**Comment by dfaulken** [comment]
How about removed?

**Comment by mboneil10** [comment]
No oops

**Comment by dfaulken** [comment]
Sorry, is that a yes? that is, we do notify other services of changes when a model is removed?

**Comment by mboneil10** [comment]
No, we don't notify other services of changes when a model is removed.

**Comment by dfaulken** [comment]
OK, let's fix that.
