### ISSUE TITLE
Param is missing or value is empty: models

### ISSUE THREAD

**Issue by Anbranin** [umts/microservices-router#19]
When making a request to the router, it seems to be needing accessible_models (specified in the yml file), when they are not technically supposed to be required. Requests should not fail based upon the absence of these models.

**Comment by dfaulken** [comment]
Just for posterity's sake, what's your rationale for `models` not being required?

**Comment by dfaulken** [comment]
https://github.com/umts/microservices-router/commit/c4497666734baae99bcc7e352b6012a405ac2830

**Comment by Anbranin** [comment]
It wasn't my idea, rather the app builders'. I thought it was because there could be a couple edge cases where an app was spun up but didn't have any models it was responsible for yet or something.

**Comment by dfaulken** [comment]
Correct — not even an edge case, really. For example our actual `microservices-ntdsurveys` doesn't serve up any data about anything. It only consumes data from other apps.
