### ISSUE TITLE
Gitignore database.yml and secrets.yml

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-router#3]
- `database.yml` could be different from person to person, and in particular _will_ be different from environment to environment;
- `secrets.yml` has secrets (which will be real ones when it comes time to deploy), so shouldn't go in a public repo.

We should create `*.yml.example` files for each.

**Comment by mboneil10** [comment]
Should there be anything specific in the example files?

**Comment by dfaulken** [comment]
Take a look at examples in our other apps - it should reflect what an actual config file should look like.

That is, I should be able to `cp database.yml.example database.yml` and have a relatively valid database config file.

**Comment by mboneil10** [comment]
01e3e47b0344b34a4e5bd184740df
68a7540cd6d51ac204e3492ee04b44de3f8074d7
