### ISSUE TITLE
Gitignore most of coverage

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-router#4]
The only part of the `coverage` directory which we need to be on GitHub is the `last_run.json` file.

**Comment by mboneil10** [comment]
Did this today.

**Comment by dfaulken** [comment]
You should be able to close issues on this repo.

**Comment by dfaulken** [comment]
And it'd be good if you could tag the commit where this happened.

**Comment by mboneil10** [comment]
Oh okay, will close them then. I'll tag the commit.

**Comment by mboneil10** [comment]
103c15f3388a4165cbd9fdf28902ebcc497
c4f682a6b5c23ae80ad7e8452
